name: CD - Deploy Docker to EC2
on: 
  workflow_run:
    workflows: ["CI Build & Push"]
    branches: [main]
    types: 
      - completed
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_IMAGE }}
  
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  EC2_IP_ADDRESS: ${{ secrets.EC2_IP_ADDRESS }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Save and Set permissions for private key
        run: |
          echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Upload deploy script (safe version)
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem scripts/deploy.sh ${{ env.EC2_USERNAME }}@${{ env.EC2_IP_ADDRESS }} :~/deploy.sh
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ env.EC2_USERNAME }}@${{ env.EC2_IP_ADDRESS }} "chmod +x ~/deploy.sh"
      - name: Run deploy script with env vars securely
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ env.EC2_USERNAME }}@${{ env.EC2_IP_ADDRESS }} <<EOF
          export DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
          export DOCKERHUB_TOKEN:"${{ secrets.DOCKERHUB_TOKEN }}"
          export DOCKERHUB_IMAGE:"${{ secrets.DOCKERHUB_IMAGE }}"
          export DOCKER_CONTAINER_NAME:"${{ secrets.DOCKER_CONTAINER_NAME }}"
          bash ~/deploy.sh
          EOF
                
  
